export const jobs = [
  {
    id: 1,
    imgProfile: '/images/logo-company.png',
    nameCompany: 'Karir Jateng',
    dibutuhkan: 'Programmer',
    category: 'Informatika',
    tipePekerjaan: 'Full Time',
    lokasi: 'Pemalang, Indonesia',
    desc: 'We search for new jobs daily from all leading job boards to bring you the best opportunities in the',
  },
  {
    id: 2,
    imgProfile: '/images/logo-company.png',
    nameCompany: 'Karir Jateng',
    dibutuhkan: 'Programmer',
    category: 'Informatika',
    tipePekerjaan: 'Full Time',
    lokasi: 'Pemalang, Indonesia',
    desc: 'We search for new jobs daily from all leading job boards to bring you the best opportunities in the',
  },
  {
    id: 3,
    imgProfile: '/images/logo-company.png',
    nameCompany: 'Karir Jateng',
    dibutuhkan: 'Programmer',
    category: 'Informatika',
    tipePekerjaan: 'Full Time',
    lokasi: 'Pemalang, Indonesia',
    desc: 'We search for new jobs daily from all leading job boards to bring you the best opportunities in the',
  },
  {
    id: 4,
    imgProfile: '/images/logo-company.png',
    nameCompany: 'Karir Jateng',
    dibutuhkan: 'Programmer',
    category: 'Informatika',
    tipePekerjaan: 'Full Time',
    lokasi: 'Pemalang, Indonesia',
    desc: 'We search for new jobs daily from all leading job boards to bring you the best opportunities in the',
  },
];
